import { Inter } from "next/font/google";
import { Audiowide } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { Skeleton } from "@/components/ui/skeleton";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });
const audiowide = Audiowide({ subsets: ["latin"], weight: '400' });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Skeleton />}>
          <Navbar />
          {children}
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
